# Generated by Django 4.0.4 on 2022-05-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sellers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=200)),
                ('zipcode', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
            ],
        ),
    ]
