# Generated by Django 4.0.4 on 2022-05-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_sellers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('number', models.PositiveIntegerField()),
            ],
        ),
    ]
